version: '3.8'

services:
  app:
    build: .
    ports:
      - "8501:8501"
    environment:
      - DATABASE_URL=postgres://${USER}:${PASSWORD}@host.docker.internal:${PORT}/${DATABASE}
      - DATABASE=${DATABASE}
      - HOST=host.docker.internal
      - USER=${USER}
      - PASSWORD=${PASSWORD}
      - PORT=${PORT}
