version: '3.8'

services:
  app:
    build: .
    ports:
      - "8501:8501"
    environment:
      - DATABASE_URL=postgres://louis:abcd@host.docker.internal:5432/SportMetrics
      - DATABASE=SportMetrics
      - HOST=host.docker.internal
      - USER=louis
      - PASSWORD=abcd
      - PORT=5432
