[[pages]]
title = "Commencer une nouvelle Session"
script = "main.py"

[[pages]]
title = "Visualisation"
script = "pages/2_Visualisation.py"

[[pages]]
title = "Créer Nouveau Sport"
script = "pages/3_Creer_nouveau_sport.py"

[[pages]]
title = "Login"
script = "pages/3_login.py"

[[pages]]
title = "Connexion"
script = "pages/4_connexion.py"

[[pages]]
title = "Déconnexion"
script = "pages/5_Deconnexion"

[[pages]]
title = "Votre Profil"
script = "pages/6_users_profile.py"  